### ISSUE TITLE
Doctors need a way to know how many patients remain to be seen

### ISSUE THREAD

**Issue by nehav39** [Intelehealth/intelehealth-doctor-webapp#3]
These are patients for which the Vitals and ADULTINITIAL encounter is complete.
However, we do not want to display patients whose visit note has been entered but the visit hasn't been ended.
The Active Visits is sorted by date, this may result in some patients who were missed to be seen remaining

**Comment by heyitskundan** [comment]
On the homepage, the doctor can sort or filter the table.
And also we have a card where we show how many active patients are there.
