### ISSUE TITLE
Dosage selection can be confusing for doctors

### ISSUE THREAD

**Issue by raunaqp** [Intelehealth/intelehealth-doctor-webapp#8]
The user (doctor) should be able to enter the dosage (in mg) of the medications entered. since the dosage will vary according to the medicines

**Comment by nehav39** [comment]
Dose -> Strength
Units -> Units (eg: mg)
(Add) Amount -> (numbers)
(Add) Units -> Units (eg: Tab/Syrup/etc.) - takes same drop down values as Units next to dose
Units next to Duration -> Units (eg: Days/Weeks/etc.)
